name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 8 * * *' # Executa todos os dias às 08:00 UTC
  workflow_dispatch: # Permite executar manualmente quando quiser

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync upstream changes
        uses: TG909/fork-sync@v2
        with:
          owner: 'dono-original-do-repo'
          base: 'main' # Ou master
          head: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}
